### ISSUE TITLE
Differences between .htaccess file and redcap_redirect.php comment

### ISSUE THREAD

**Issue by kirenotneb** [susom/redcap-redirect#4]
We recently switched servers (RedHat :arrow_right: Ubuntu) both with Apache 2.4. Previously, we were using the `.htaccess` approach to perform the Rewrite, but with the new server we opted to set it up in the main Apache configuration. We noticed that some URLs stopped working correctly after the migration, specifically any URLs that omitted the `index.php` as part of the address. For example: https://example.edu/redcap_v10.7.1/ExternalModules/?prefix=api_sync&page=api-sync&pid=9999, does not include the `index.php` after the `ExternalModules` part of the path. This was triggering the plugin to return a 404, with the plugin 404 styling.

While troubleshooting I noticed a difference between the [.htaccess](../blob/master/.htaccess) and [redcap_redirect.php](../blob/master/redcap_redirect.php) 

```
9c26
<         RewriteRule "^(.+)$"     "/redcap_redirect.php"   [PT,L]
---
>         RewriteRule "^(.+)$"     "/redcap_redirect.php"   [PT,L,NS]
```
It appears the missing `NS` flag prevents the plugin from accepting the implicit `index.php`. After updating the Apache config including the missing `NS` flag it began redirecting correctly to all the addresses.

**Comment by 123andy** [comment]
Do you have the latest version of redcap_redirect?  The NS flag has been there for a while I think...

**Comment by kirenotneb** [comment]
I made sure to update the redcap_redirect.php just before troubleshooting again, but this difference is between the .htaccess file and the comment in the redcap_redirect file.

**Comment by aarenson** [comment]
Agreeing with kirenotneb that .htaccess looks like it should be updated to use NS on the RewriteRule

**Comment by 123andy** [comment]
I modified the .htaccess -  9668d1374886b3c6fca14bf8aa2b8fc86c2011d5.
